### ISSUE TITLE
Rake aborted when running db:migrate

### ISSUE THREAD

**Issue by rsleventhal** [oliverguenther/openproject-revisions_git#1]
Adding openproject-revisions and openproject-revisions_git to the Gemfile.plugins file and running `RIALS_ENV=production bundle exec rake db:migrate` leads to `rake aborted!` with the following error:

```
require 'rails/all'... 3.140s
Bundler.require... 13.750s
Application.initialize!... [deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
33.220s
rake aborted!
SyntaxError: /home/openproject/.bundler/ruby/1.9.1/openproject-revisions_git-67023821ec55/db/migrate/20140530181302_aggregated_git_hosting_migrations.rb:82: syntax error, unexpected $end, expecting keyword_end
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/migration.rb:537:in `load_migration'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/migration.rb:533:in `migration'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/migration.rb:528:in `migrate'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/migration.rb:777:in `call'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/migration.rb:777:in `ddl_transaction'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/migration.rb:719:in `block in migrate'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/migration.rb:700:in `each'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/migration.rb:700:in `migrate'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/migration.rb:570:in `up'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/migration.rb:551:in `migrate'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/railties/databases.rake:193:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by rsleventhal** [comment]
Potential work around:
Added two extra `end`s to the 20140530181302_aggregated_git_hosting_migrations.rb script and the error was bypassed.

**Comment by oliverguenther** [comment]
Rookie mistake, sorry :/ In the process of removing several unused migrations from the fork in 8456d93f,  I've deleted too much and it didn't occur to me to run the migrations again. Sorry, should be fixed!

**Comment by rsleventhal** [comment]
No worries.  I'm glad it's working and that it's confirmed :)

Thanks for the speedy reply!
