### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by JohnDoe42** [oliverguenther/openproject-revisions_git#11]
I get this, when I try to install the plugin (openproject:stable):

```
~/openproject (git)-[stable] % RAILS_ENV="production" bundle exec rake db:seed --trace               :(
require 'rails/all'... 0.330s
Bundler.require... 0.880s
** Invoke db:seed (first_time)
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment (first_time)
** Execute environment
Application.initialize!... rake aborted!
TypeError: can't clone NilClass
/srv/http/openproject/vendor/bundle/ruby/2.1.0/bundler/gems/openproject-revisions_git-b8a03f879dea/lib/open_project/revisions/git/patches/setting_patch.rb:20:in `clone'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/bundler/gems/openproject-revisions_git-b8a03f879dea/lib/open_project/revisions/git/patches/setting_patch.rb:20:in `<module:InstanceMethods>'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/bundler/gems/openproject-revisions_git-b8a03f879dea/lib/open_project/revisions/git/patches/setting_patch.rb:17:in `<module:SettingPatch>'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/bundler/gems/openproject-revisions_git-b8a03f879dea/lib/open_project/revisions/git/patches/setting_patch.rb:5:in `<module:Patches>'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/bundler/gems/openproject-revisions_git-b8a03f879dea/lib/open_project/revisions/git/patches/setting_patch.rb:4:in `<module:Git>'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/bundler/gems/openproject-revisions_git-b8a03f879dea/lib/open_project/revisions/git/patches/setting_patch.rb:3:in `<top (required)>'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:359:in `require_or_load'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:313:in `depend_on'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:225:in `require_dependency'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/bundler/gems/openproject-revisions_git-b8a03f879dea/lib/open_project/revisions/git/engine.rb:91:in `block (2 levels) in <class:Engine>'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/bundler/gems/openproject-revisions_git-b8a03f879dea/lib/open_project/revisions/git/engine.rb:90:in `each'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/bundler/gems/openproject-revisions_git-b8a03f879dea/lib/open_project/revisions/git/engine.rb:90:in `block in <class:Engine>'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:649:in `_run__361885902556550655__prepare__3031345104535160070__callbacks'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `block in run_initializers'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
/srv/http/openproject/config/environment.rb:36:in `block in <top (required)>'
/srv/http/openproject/config/application.rb:44:in `block in bench'
/usr/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
/srv/http/openproject/config/application.rb:43:in `bench'
/srv/http/openproject/config/environment.rb:34:in `<top (required)>'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/application.rb:103:in `require_environment!'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/railties/databases.rake:346:in `block (2 levels) in <top (required)>'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'
/srv/http/openproject/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => db:abort_if_pending_migrations => environment
```

**Comment by oliverguenther** [comment]
Hi, thanks for your feedback. Please test if ea4a5a7 fixes the error.

**Comment by JohnDoe42** [comment]
Works, thanks!
